# Generated by Django 4.1.5 on 2023-01-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/images/product/image.png', null=True, upload_to='images/product'),
        ),
    ]
